#!/usr/bin/sh

colorflag='-G'

alias l='ls'
alias ls='ls ${colorflag}'
alias lsd='ls -l | grep "^d"'
alias lsh='ls -a | grep "^\."'

alias ipynb='ipython notebook'
alias py='python'
alias v='vim'
alias server='python -m SimpleHTTPServer'
alias opencrontab='env EDITOR=nano crontab -e'

# navigation aliases
alias ..="cd .."
alias c='clear'
alias code='cd ~/code'
alias github='code && cd github'
alias bashrc='vim ~/.bashrc'
alias vimrc='vim ~/.vimrc'

# build/run aliases
alias cppcompile='c++ -std=c++11 -stdlib=libc++'
alias activate='source venv/bin/activate'
alias pyinstall='python setup.py install'
alias pyclean='rm -rf __pycache__ *.pyc'
alias resume='python ~/code/github/scripts/resume/resume.py'
alias jot='python ~/code/github/jot/jot.py'

# git aliases
alias gst='git status'
alias gcm='git commit'
alias gph='git push'
alias glg='git log -10 --graph --pretty="%C(bold green)%h%Creset %C(yellow)%an%Creset%C(auto)%d%Creset %s"'
alias gdf='git diff'
alias gck='git checkout'
alias gbr='git branch'
alias gad='git add'
alias gsh='git show'
alias gmg='git merge --ff-only'
alias grb='git rebase'
alias gls='git ls-tree'

alias grep='grep --color=auto'
alias refresh='source ~/.bash_profile'
alias diff='colordiff'

# show and hide . files
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool True && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool False && killall Finder"
